### ISSUE TITLE
Audiobook hours uwu

### ISSUE THREAD

**Issue by mistcurve** [Swiddis/word-debt-bot#4]
Can we pweaaaase hab audiobook hours? uwu

wie cool wäre das sein??

bitte bitte bitte bitte bitte bitteeee

**Comment by Swiddis** [comment]
Kann es vielleicht später versuchen, weiß nicht eine Zeit, etwa nach 1.0 wahrscheinlich.

**Comment by Swiddis** [comment]
Average reading aloud pace is 135 wpm w/ 135*60=8100, thinking of counting each hour as 8000 words for the rest of the math.

```txt
> .log 2.5 hours
Logged 2.5 hours! New debt: 2,000
```
