### ISSUE TITLE
Help command

### ISSUE THREAD

**Issue by Swiddis** [Swiddis/word-debt-bot#6]
People gotta learn how to use this thing!

The `.help` command is included by default in `discord.py`, but the commands added don't have any real description included, making it not particularly useful. Let's add some descriptions on what the different commands do. It might also be worth renaming the cogs to something more intuitive.

**Comment by sumofall7171** [comment]
.log - Adds words and clears debt
.help - Provides knowledge about the bot
.ping - Checks to see if the bot is running.
.register - Adds you to the bot so you can begin to add words
.version - Displays the current version

Inside the .help command the rules of the game being displayed would be useful as currently the only way to see the rules is in the pinned comment or in the google drive.

(This was typed up pretty quickly. sorry)
